# Generated by Django 2.0.5 on 2018-06-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Luffy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='modules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Luffy.Module', verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='summarys',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Luffy.Summary', verbose_name='用户总结'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Luffy.Team', verbose_name='所属小组'),
        ),
    ]
