# Generated by Django 2.0.5 on 2018-06-22 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Luffy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.TextField(verbose_name='评论内容')),
            ],
        ),
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('isUp', models.BooleanField(verbose_name='点赞')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=32, verbose_name='模块名称')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=64, verbose_name='分享描述')),
                ('content', models.TextField(verbose_name='分享内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('commentCount', models.IntegerField(verbose_name='评论数')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('abstract', models.CharField(max_length=64, null=True, verbose_name='总结摘要')),
                ('today_content', models.TextField(default=1, verbose_name='今天内容')),
                ('tomorrow_content', models.TextField(default=1, verbose_name='明天计划')),
                ('code', models.IntegerField(default=1, verbose_name='代码量')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('complete', models.BooleanField(choices=[(0, 'no'), (1, 'yes')], default=0, verbose_name='是否完成任务')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=16, verbose_name='小组名称')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('classify', models.CharField(max_length=12, verbose_name='总结分类')),
            ],
        ),
        migrations.CreateModel(
            name='UrlShare',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(default='xx', max_length=20, verbose_name='博客概要')),
                ('desc', models.TextField(verbose_name='博客知识点概要')),
                ('url', models.URLField(verbose_name='分享博客地址')),
                ('isFavor', models.IntegerField(verbose_name='点赞数')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='url',
            field=models.URLField(null=True, verbose_name='博客地址'),
        ),
        migrations.AddField(
            model_name='urlshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='summary',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Luffy.Types', verbose_name='总结类型'),
        ),
        migrations.AddField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='所属学员'),
        ),
        migrations.AddField(
            model_name='share',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='所属学员'),
        ),
        migrations.AddField(
            model_name='favor',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Luffy.UrlShare'),
        ),
        migrations.AddField(
            model_name='favor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Luffy.Share'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='modules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Luffy.Module', verbose_name='所属模块'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Luffy.Team', verbose_name='所属小组'),
        ),
    ]
