# Generated by Django 2.0.5 on 2018-06-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luffy', '0003_auto_20180619_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='content',
        ),
        migrations.AddField(
            model_name='summary',
            name='today_content',
            field=models.TextField(default=1, verbose_name='今天内容'),
        ),
        migrations.AddField(
            model_name='summary',
            name='tomorrow_content',
            field=models.TextField(default=1, verbose_name='明天计划'),
        ),
    ]
