# Generated by Django 2.0.5 on 2018-06-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luffy', '0004_auto_20180619_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='code',
            field=models.IntegerField(default=1, verbose_name='代码量'),
        ),
    ]
