# Generated by Django 2.0.5 on 2018-06-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luffy', '0006_auto_20180619_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshare',
            name='desc',
            field=models.CharField(default='xx', max_length=64, verbose_name='博客知识点概要'),
        ),
        migrations.AddField(
            model_name='urlshare',
            name='title',
            field=models.CharField(default='xx', max_length=20, verbose_name='博客概要'),
        ),
    ]
