# Generated by Django 2.0.5 on 2018-06-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luffy', '0007_auto_20180620_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshare',
            name='desc',
            field=models.TextField(verbose_name='博客知识点概要'),
        ),
    ]
