# Generated by Django 2.0.5 on 2018-06-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luffy', '0008_auto_20180620_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
