# Generated by Django 2.0.5 on 2018-06-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luffy', '0009_auto_20180620_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='signature',
            field=models.CharField(default='如果你有理想的话,就努力去实现', max_length=32, verbose_name='签名'),
        ),
    ]
