# Generated by Django 2.0.5 on 2018-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luffy', '0010_userinfo_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
